# ===================================================================
# INTERRUPTOR MAESTRO DE PERFILES
# ===================================================================
# Escribe 'dev' para usar tu base de datos local (tu computadora)
# Escribe 'prod' para usar tu base de datos en la nube (Microsoft Azure)
spring.profiles.active=dev

# Puerto del servidor web
server.port=8080

# Configuración común de JPA / Hibernate (Se aplica en ambos entornos)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true 