# CONEXIÓN EN LA NUBE (MICROSOFT AZURE - CANADÁ)
spring.datasource.url=jdbc:postgresql://his-hospital-db-server.postgres.database.azure.com:5432/his_db?sslmode=require
spring.datasource.username=adminhis
spring.datasource.password=plantasVs2
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true